/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlinebloodbank;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author shamimul
 */
public class regform extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;

    /**
     * Creates new form regform
     */
    public regform() {
        initComponents();
         setLocation(200,10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlebel1 = new javax.swing.JLabel();
        jlebel2 = new javax.swing.JLabel();
        jlebel4 = new javax.swing.JLabel();
        jlebel5 = new javax.swing.JLabel();
        jLebel8 = new javax.swing.JLabel();
        jlebel6 = new javax.swing.JLabel();
        jlebel7 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtcontactno = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        txtreset = new javax.swing.JButton();
        jregButton = new javax.swing.JButton();
        gotoupdt = new javax.swing.JButton();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        jlebel3 = new javax.swing.JLabel();
        gotohome = new javax.swing.JButton();
        prevpg = new javax.swing.JButton();
        txtgndr = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtbg = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlebel1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jlebel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlebel1.setText("First Name");

        jlebel2.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jlebel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlebel2.setText("Last Name");

        jlebel4.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jlebel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlebel4.setText("Contact NO");

        jlebel5.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jlebel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlebel5.setText("Email Address");

        jLebel8.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLebel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLebel8.setText("Password");

        jlebel6.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jlebel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlebel6.setText("Gender");

        jlebel7.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jlebel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlebel7.setText("Address");

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });

        txtreset.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        txtreset.setText("Reset");
        txtreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresetActionPerformed(evt);
            }
        });

        jregButton.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jregButton.setText("Register");
        jregButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregButtonActionPerformed(evt);
            }
        });

        gotoupdt.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gotoupdt.setText("Click Here To Update Info.");
        gotoupdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoupdtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registration");

        jlebel3.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jlebel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlebel3.setText("User Name");

        gotohome.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        gotohome.setText("Home");
        gotohome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotohomeActionPerformed(evt);
            }
        });

        prevpg.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        prevpg.setText("<-- Back");
        prevpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevpgActionPerformed(evt);
            }
        });

        txtgndr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtgndr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others", " " }));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Blood Group");

        txtbg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtbg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        txtbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbgActionPerformed(evt);
            }
        });

        txtadd.setColumns(20);
        txtadd.setRows(5);
        jScrollPane1.setViewportView(txtadd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtreset, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jregButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlebel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlebel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlebel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlebel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlebel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlebel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLebel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlebel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 602, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcontactno)
                            .addComponent(txtlname)
                            .addComponent(txtemail)
                            .addComponent(txtuname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtfname, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(txtbg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtgndr, 0, 254, Short.MAX_VALUE)
                            .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gotohome, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prevpg, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(gotoupdt, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlebel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlebel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlebel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlebel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontactno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlebel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlebel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgndr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlebel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLebel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jregButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtreset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gotoupdt)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prevpg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gotohome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotoupdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoupdtActionPerformed
        new updater().setVisible(true);
        dispose();
    }//GEN-LAST:event_gotoupdtActionPerformed

    private void jregButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregButtonActionPerformed
        try{
          String query = "INSERT INTO `registration`( `First Name`, `Last Name`, `User Name`, `Contact No`, `E-mail Address`, `Gender`, `Blood Group`, `Address`, `Password`) VALUES (?,?,?,?,?,?,?,?,?)";
          con = DriverManager.getConnection("jdbc:mysql://localhost/bloodbankdb","root","");
          pst = con.prepareStatement(query);
          pst.setString(1,txtfname.getText());
          pst.setString(2,txtlname.getText());
          pst.setString(3,txtuname.getText());
          pst.setString(4,txtcontactno.getText());
          pst.setString(5,txtemail.getText());
          pst.setString(6,txtgndr.getSelectedItem().toString());
          pst.setString(7,txtbg.getSelectedItem().toString());
          pst.setString(8,txtadd.getText());
          pst.setString(9,txtpass.getText());
          pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registration Complete");
          
          
          
        }catch(Exception ex){
         JOptionPane.showMessageDialog(null, ex);   
        }
        
        
    }//GEN-LAST:event_jregButtonActionPerformed

    private void txtresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresetActionPerformed
       txtfname.setText("");
       txtlname.setText("");
       txtuname.setText("");
       txtcontactno.setText("");
       txtemail.setText("");
       txtadd.setText("");
       txtpass.setText("");
      
    }//GEN-LAST:event_txtresetActionPerformed

    private void gotohomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotohomeActionPerformed
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_gotohomeActionPerformed

    private void prevpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevpgActionPerformed
        new Donor().setVisible(true);
        dispose();
    }//GEN-LAST:event_prevpgActionPerformed

    private void txtbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbgActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gotohome;
    private javax.swing.JButton gotoupdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLebel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlebel1;
    private javax.swing.JLabel jlebel2;
    private javax.swing.JLabel jlebel3;
    private javax.swing.JLabel jlebel4;
    private javax.swing.JLabel jlebel5;
    private javax.swing.JLabel jlebel6;
    private javax.swing.JLabel jlebel7;
    private javax.swing.JButton jregButton;
    private javax.swing.JButton prevpg;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JComboBox<String> txtbg;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JComboBox<String> txtgndr;
    private javax.swing.JTextField txtlname;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JButton txtreset;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
